### ISSUE TITLE
not a issue, but a question!

### ISSUE THREAD

**Issue by GoatlyHorisions** [KnownSH/FiguraSVC#1]
well, since modrinth doesn't have any sort of comment feature, and i wanted to ask a question, is there any chance of a forge port of this? would love to use this, buuut im a forge user

if not then thats fine, but i just wanted to ask, thats all

**Comment by KnownSH** [comment]
V2 will have Forge/NeoForge support, ETA on it is uncertain tho.
V1 was only on Fabric just due to my laziness.
